source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KrWebRTC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  target 'KrWebRTCTests' do
    inherit! :search_paths
    pod 'Starscream', '~> 4.0.4'
    # Pods for testing
  end

  target 'KrWebRTCUITests' do
    # Pods for testing
  end

end
