source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebRTC-Sample-IOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KrWebRTC
  pod 'Starscream', '~> 4.0.4'

  target 'WebRTC-Sample-IOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebRTC-Sample-IOSUITests' do
    # Pods for testing
  end

end
